### ISSUE TITLE
anti afk 

### ISSUE THREAD

**Issue by Gegecito** [NoTwistedHere/Roblox#3]
`
repeat task.wait() until game:IsLoaded()

task.spawn(function()
while true do
		task.wait(5)
	local succ, err = pcall(function()
	if game:FindService("VirtualInputManager") then
		print("detected")
			end
		end)
		if not succ then
			print("wow detected tf")
		end
	end
	task.wait(10)
	game:GetService("VirtualInputManager")
	while true do
		task.wait(5)
		local succ, err = pcall(function()
		if not game:FindService("VirtualInputManager") then
			print("wat the fuck detected")
			end
		end)
		if not succ then
			print("wow detected tf")
		end
	end
end)`
updated detection

**Comment by NoTwistedHere** [comment]
Thanks for the report, forgot that FindService returns nil 😅
