### ISSUE TITLE
Red

### ISSUE THREAD

**Issue by Romanata109** [NoTwistedHere/Roblox#6]
![IMG_0032](https://github.com/user-attachments/assets/35a134e7-9a6c-41bf-a631-c30fe6ee5c3a)

**Comment by Romanata109** [comment]
![IMG_0029](https://github.com/user-attachments/assets/ed096ed6-72e1-4061-9d25-4b81ea48f73a)

**Comment by Romanata109** [comment]
![Uploading IMG_0031.jpeg…]()

**Comment by Romanata109** [comment]
![Uploading IMG_0033.jpeg…]()

**Comment by NoTwistedHere** [comment]
This is nothing to do with me or this repo
